[package]
name = "pentagon"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = {workspace = true}
wgpu = {workspace = true}
winit = {workspace = true}
memory = {path = "../../crates/memory"}
tinyge-graphics = {path = "../../crates/graphics"}
codegen-macros = {path = "../../crates/codegen-macros"}